<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <IsTestProject>true</IsTestProject>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bblanchon.PDFium.Win32" Version="150.0.7869" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PdfExplorer.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <_PdfiumSrc>$([MSBuild]::NormalizePath('$(TargetDir)..\runtimes\win-x64\native\pdfium.dll'))</_PdfiumSrc>
    <_PdfiumDst>$([MSBuild]::NormalizePath('$(TargetDir)..\pdfium.dll'))</_PdfiumDst>
  </PropertyGroup>
  <Target Name="CopyPdfiumToRoot"
          AfterTargets="Build"
          Inputs="$(_PdfiumSrc)"
          Outputs="$(_PdfiumDst)">
    <Copy
      SourceFiles="$(_PdfiumSrc)"
      DestinationFiles="$(_PdfiumDst)"
      SkipUnchangedFiles="true"
      Condition="Exists('$(_PdfiumSrc)')" />
  </Target>

</Project>
