<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);PdfExplorer.Tests/**</DefaultItemExcludes>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\target\release\pdf_extractor_capi.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>

</Project>
