[package]
name = "pdf_extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
lopdf = "0.34"
rusqlite = { version = "0.32", features = ["bundled"] }
xxhash-rust = { version = "0.8", features = ["xxh3"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
anyhow = "1"
unicode-normalization = "0.1"
chrono = "0.4"
crossbeam-channel = "0.5"
rayon = "1"
num_cpus = "1"
tantivy = "0.22"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
tempfile = "3"
regex = "1.12.3"
imageproc = "0.25"
whatlang = "0.18.0"
lindera = { version = "3", default-features = false, features = ["embed-ipadic"] }

[lib]
name = "pdf_extractor"
path = "src/lib.rs"

[[bin]]
name = "tesseract_worker"
path = "src/bin/tesseract_worker.rs"

